name: ii

on:
  push:
    branches: [ main ]
    
jobs:
    deploy:
        runs-on: self-hosted
    
  
            
        steps:
        - uses: actions/checkout@v2
        - run: npm install
        - run: npm run build --if-present
        - run: npm test
        - run: npm run dev
